//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Author { get; set; }
        public short Rating { get; set; }
        public string Content { get; set; }

        [JsonIgnore]
        public virtual Member Member { get; set; }
        [JsonIgnore]
        public virtual Product Product1 { get; set; }
    }
}
