//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ReportComment = new HashSet<ReportComment>();
        }
    
        public int Id { get; set; }
        public int Product { get; set; }
        public int Author { get; set; }
        public short Rating { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportComment> ReportComment { get; set; }
    }
}
