//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Source { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public Nullable<int> Image { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string Link { get; set; }
    
        public virtual Image Image1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Source Source1 { get; set; }
    }
}
